# Generated by Django 4.2.4 on 2023-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='secondname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
    ]
