print("")
print("Заполните информацию...")
print("")
name = input("Имя: ")
surname = input("Фамилия: ")
age = int(input("Возраст: "))
hobby = input("Хобби: ")
weight = int(input("Вес: "))
height = int(input("Рост: "))
print("")
print("Имя: " + name)
print("Фамилия: " + surname)
print("Возраст: " + str(age))
print("Хобби: " + hobby)
print("Вес: " + str(weight))
print("Рост: " + str(height))
print("Ваша толстота: " + str(weight/height))

print("Вам: " + str(age//10) + " десятков лет")